//tablecrafting defines
#define CAT_NONE	""
#define CAT_WEAPONRY	"Weaponry"
#define CAT_WEAPON	"Weapons"
#define CAT_AMMO	"Ammunition"
#define CAT_PRIMAL  "Tribal"
#define CAT_GOULASH	 "Goulashes"
#define CAT_SHISHKEBAB	 "Shishkebabs"
#define CAT_FERMENTED	 "Fermented"
#define CAT_PASHTET	 "Pashtets"
#define CAT_CORNED	 "Corned"
#define CAT_SOUPS	 "Soups"
#define CAT_RICEDISH	 "Rice Dishes"
