
#define DEFAULT_AMBIENT_ENVIRONMENT_NIGHT list(\
	'sound/stalker/ambience/rnd_outdoor_night/ambient_night_1.ogg',\
	'sound/stalker/ambience/rnd_outdoor_night/ambient_night_2.ogg',\
	'sound/stalker/ambience/rnd_outdoor_night/ambient_night_3.ogg',\
	'sound/stalker/ambience/rnd_outdoor_night/ambient_night_4.ogg',\
	'sound/stalker/ambience/rnd_outdoor_night/ambient_night_5.ogg',\
	'sound/stalker/ambience/rnd_outdoor_night/ambient_night_6.ogg',\
	'sound/stalker/ambience/rnd_outdoor_night/ambient_night_7.ogg',\
	'sound/stalker/ambience/rnd_outdoor_night/ambient_night_8.ogg',\
	'sound/stalker/ambience/rnd_outdoor_night/ambient_night_9.ogg',\
	'sound/stalker/ambience/rnd_outdoor_night/ambient_night_10.ogg',\
	'sound/stalker/ambience/rnd_outdoor_night/ambient_night_11.ogg',\
	'sound/stalker/ambience/rnd_outdoor_night/ambient_night_12.ogg',\
	'sound/stalker/ambience/rnd_outdoor_night/ambient_night_13.ogg',\
	'sound/stalker/ambience/rnd_outdoor_night/rnd_moan.ogg',\
	'sound/stalker/ambience/rnd_outdoor_night/rnd_moan1.ogg',\
	'sound/stalker/ambience/rnd_outdoor_night/rnd_moan2.ogg',\
	'sound/stalker/ambience/rnd_outdoor_night/rnd_moan3.ogg',\
	'sound/stalker/ambience/rnd_outdoor_night/rnd_moan4.ogg',\
	'sound/stalker/ambience/rnd_outdoor_night/rnd_moan5.ogg',\
	'sound/stalker/ambience/rnd_outdoor_night/rnd_moan6.ogg',\
	'sound/stalker/ambience/rnd_outdoor_night/rnd_night_amb_1.ogg',\
	'sound/stalker/ambience/rnd_outdoor_night/rnd_night_amb_2.ogg',\
	'sound/stalker/ambience/rnd_outdoor_night/rnd_night_amb_3.ogg',\
	'sound/stalker/ambience/rnd_outdoor_night/wolf_howl_01.ogg',\
	'sound/stalker/ambience/rnd_outdoor_night/wolf_howl_02.ogg',\
	'sound/stalker/ambience/rnd_outdoor_night/wolf_howl_03.ogg',\
	'sound/stalker/ambience/rnd_outdoor_night/wolf_howl_04.ogg',\
	'sound/stalker/ambience/rnd_outdoor_night/wolf_howl_05.ogg',\
	'sound/stalker/ambience/rnd_outdoor_night/wolf_howl_06.ogg',\
	'sound/stalker/ambience/rnd_outdoor_night/wolf_howl_07.ogg',\
	'sound/stalker/ambience/rnd_outdoor_night/zat_bkg_tuman.ogg'\
	)
